Namespace QuestInfo
    Public Class LocationList
        Public Shared Locations As Dictionary(Of Integer, String) = New Dictionary(Of Integer, String)() From {
    {1, "Siege Fortress Day"},
    {2, "Forest and Hills Day"},
    {3, "Desert Day"},
    {4, "Swamp Day"},
    {5, "Volcano Day"},
    {6, "Jungle Day"},
    {7, "Castle Schrade"},
    {8, "Crimson Battleground"},
    {9, "Arena with Ledge Day"},
    {10, "Arena with Pillar Day"},
    {11, "Snowy Mountains Day"},
    {12, "Town Siege Day"},
    {13, "Tower 1"},
    {14, "Tower 2"},
    {15, "Tower 3"},
    {16, "Forest and Hills Night"},
    {17, "Desert Night"},
    {18, "Swamp Night"},
    {19, "Volcano Night"},
    {20, "Jungle Night"},
    {21, "Snowy Mountains Night"},
    {22, "Town Siege night"},
    {23, "Siege Fortress Night"},
    {24, "Arena with Ledge Night"},
    {25, "Arena with Pillar Night"},
    {26, "Great Forest Day"},
    {27, "Great Forest Night"},
    {28, "Volcano 2 Day"},
    {29, "Volcano 2 Night"},
    {30, "Jungle Dream"},
    {31, "Gorge Day"},
    {32, "Gorge Night"},
    {35, "Battlefield Day"},
    {44, "Top of Great Forest"},
    {45, "Caravan Balloon Day"},
    {46, "Caravan Balloon Night"},
    {47, "Solitude Isle 1"},
    {48, "Solitude Isle 2"},
    {49, "Solitude Isle 3"},
    {50, "Highlands Day"},
    {51, "Highlands Night"},
    {52, "Tower with Nesthole"},
    {53, "Arena with Moat Day"},
    {54, "Arena with Moat Night"},
    {55, "Fortress Day"},
    {56, "Fortress Night"},
    {57, "Tidal Island Day"},
    {58, "Tidal Island Night"},
    {60, "Polar Sea Day"},
    {61, "Polar Sea Night"},
    {62, "World's End"},
    {63, "Large Airship"},
    {64, "Flower Field Day"},
    {65, "Flower Field Night"},
    {66, "Deep Crater"},
    {67, "Bamboo Forest Day"},
    {68, "Bamboo Forest Night"},
    {69, "Battlefield 2 Day"},
    {70, "Unimplemented map"},
    {71, "1st Dist Tower 1"},
    {72, "1st Dist Tower 2"},
    {73, "2nd Dist Tower 1"},
    {74, "2nd Dist Tower 2"},
    {75, "Urgent Tower"},
    {76, "3rd Dist Tower"},
    {77, "3rd Dist Tower 2?"},
    {78, "4th Dist Tower"},
    {79, "White Lake Day"},
    {80, "White Lake Night"},
    {81, "Solitude Depths Slay 1"},
    {82, "Solitude Depths Slay 2?"},
    {83, "Solitude Depths Slay 3?"},
    {84, "Solitude Depths Slay 4?"},
    {85, "Solitude Depths Slay 5?"},
    {86, "Solitude Depths Support 1"},
    {87, "Solitude Depths Support 2"},
    {88, "Solitude Depths Support 3"},
    {89, "Solitude Depths Support 4"},
    {90, "Solitude Depths Support 5"},
    {91, "Cloud Viewing Fortress"},
    {92, "Painted Falls Day"},
    {93, "Painted Falls Night"},
    {94, "Sanctuary"},
    {95, "Hunter's Road"},
    {96, "Sacred Pinnacle"},
    {97, "Historic Site"}
}
    End Class
End Namespace