Namespace QuestInfo
    Public Class Monsters
        Public Shared MonsterNames As Dictionary(Of Byte, String) = New Dictionary(Of Byte, String)() From {
    {&H0, "None"},
    {&H1, "Rathian"},
    {&H2, "Fatalis"},
    {&H3, "Kelbi"},
    {&H4, "Mosswine"},
    {&H5, "Bullfango"},
    {&H6, "Yian Kut-Ku"},
    {&H7, "Lao-Shan Lung"},
    {&H8, "Cephadrome"},
    {&H9, "Felyne"},
    {&HA, "Veggie Elder"},
    {&HB, "Rathalos"},
    {&HC, "Aptonoth"},
    {&HD, "Genprey"},
    {&HE, "Diablos"},
    {&HF, "Khezu"},
    {&H10, "Velociprey"},
    {&H11, "Gravios"},
    {&H12, "Felyne?"},
    {&H13, "Vespoid"},
    {&H14, "Gypceros"},
    {&H15, "Plesioth"},
    {&H16, "Basarios"},
    {&H17, "Melynx"},
    {&H18, "Hornetaur"},
    {&H19, "Apceros"},
    {&H1A, "Monoblos"},
    {&H1B, "Velocidrome"},
    {&H1C, "Gendrome"},
    {&H1D, "Rocks"},
    {&H1E, "Ioprey"},
    {&H1F, "Iodrome"},
    {&H20, "Pugis"},
    {&H21, "Kirin"},
    {&H22, "Cephalos"},
    {&H23, "Giaprey / Giadrome"},
    {&H24, "Crimson Fatalis"},
    {&H25, "Pink Rathian"},
    {&H26, "Blue Yian Kut-Ku"},
    {&H27, "Purple Gypceros"},
    {&H28, "Yian Garuga"},
    {&H29, "Silver Rathalos"},
    {&H2A, "Gold Rathian"},
    {&H2B, "Black Diablos"},
    {&H2C, "White Monoblos"},
    {&H2D, "Red Khezu"},
    {&H2E, "Green Plesioth"},
    {&H2F, "Black Gravios"},
    {&H30, "Daimyo Hermitaur"},
    {&H31, "Azure Rathalos"},
    {&H32, "Ashen Lao-Shan Lung"},
    {&H33, "Blangonga"},
    {&H34, "Congalala"},
    {&H35, "Rajang"},
    {&H36, "Kushala Daora"},
    {&H37, "Shen Gaoren"},
    {&H38, "Great Thunderbug"},
    {&H39, "Shakalaka"},
    {&H3A, "Yama Tsukami"},
    {&H3B, "Chameleos"},
    {&H3C, "Rusted Kushala Daora"},
    {&H3D, "Blango"},
    {&H3E, "Conga"},
    {&H3F, "Remobra"},
    {&H40, "Lunastra"},
    {&H41, "Teostra"},
    {&H42, "Hermitaur"},
    {&H43, "Shogun Ceanataur"},
    {&H44, "Bulldrome"},
    {&H45, "Anteka"},
    {&H46, "Popo"},
    {&H47, "White Fatalis"},
    {&H48, "Yama Tsukami"},
    {&H49, "Ceanataur"},
    {&H4A, "Hypnocatrice"},
    {&H4B, "Lavasioth"},
    {&H4C, "Tigrex"},
    {&H4D, "Akantor"},
    {&H4E, "Bright Hypnoc"},
    {&H4F, "Lavasioth Subspecies"},
    {&H50, "Espinas"},
    {&H51, "Orange Espinas"},
    {&H52, "White Hypnoc"},
    {&H53, "Akura Vashimu"},
    {&H54, "Akura Jebia"},
    {&H55, "Berukyurosu"},
    {&H56, "Cactus"},
    {&H57, "Gorge Objects"},
    {&H58, "Gorge Rocks"},
    {&H59, "Pariapuria"},
    {&H5A, "White Espinas"},
    {&H5B, "Kamu Orugaron"},
    {&H5C, "Nono Orugaron"},
    {&H5D, "Raviente"},
    {&H5E, "Dyuragaua"},
    {&H5F, "Doragyurosu"},
    {&H60, "Gurenzeburu"},
    {&H61, "Burukku"},
    {&H62, "Erupe"},
    {&H63, "Rukodiora"},
    {&H64, "Unknown"},
    {&H65, "Gogomoa"},
    {&H66, "Kokomoa"},
    {&H67, "Taikun Zamuza"},
    {&H68, "Abiorugu"},
    {&H69, "Kuarusepusu"},
    {&H6A, "Odibatorasu"},
    {&H6B, "Disufiroa"},
    {&H6C, "Rebidiora"},
    {&H6D, "Anorupatisu"},
    {&H6E, "Hyujikiki"},
    {&H6F, "Midogaron"},
    {&H70, "Giaorugu"},
    {&H71, "Mi Ru"},
    {&H72, "Farunokku"},
    {&H73, "Pokaradon"},
    {&H74, "Shantien"},
    {&H75, "Pokara"},
    {&H76, "Dummy"},
    {&H77, "Goruganosu"},
    {&H78, "Aruganosu"},
    {&H79, "Baruragaru"},
    {&H7A, "Zerureusu"},
    {&H7B, "Gougarf"},
    {&H7C, "Uruki"},
    {&H7D, "Forokururu"},
    {&H7E, "Meraginasu"},
    {&H7F, "Diorekkusu"},
    {&H80, "Garuba Daora"},
    {&H81, "Inagami"},
    {&H82, "Varusaburosu"},
    {&H83, "Poborubarumu"},
    {&H84, "Duremudira"},
    {&H85, "UNK"},
    {&H86, "Felyne"},
    {&H87, "Blue NPC"},
    {&H88, "UNK"},
    {&H89, "Cactus"},
    {&H8A, "Veggie Elders"},
    {&H8B, "Gureadomosu"},
    {&H8C, "Harudomerugu"},
    {&H8D, "Toridcless"},
    {&H8E, "Gasurabazura"},
    {&H8F, "Kusubami"},
    {&H90, "Yama Kurai"},
    {&H91, "Dure 3rd Phase"},
    {&H92, "Zinogre"},
    {&H93, "Deviljho"},
    {&H94, "Brachydios"},
    {&H95, "Berserk Laviente"},
    {&H96, "Toa Tesukatora"},
    {&H97, "Barioth"},
    {&H98, "Uragaan"},
    {&H99, "Stygian Zinogre"},
    {&H9A, "Guanzorumu"},
    {&H9B, "Starving Deviljho"},
    {&H9C, "UNK"},
    {&H9D, "Egyurasu"},
    {&H9E, "Voljang"},
    {&H9F, "Nargacuga"},
    {&HA0, "Keoaruboru"},
    {&HA1, "Zenaserisu"},
    {&HA2, "Gore Magala"},
    {&HA3, "Blinking Nargacuga"},
    {&HA4, "Shagaru Magala"},
    {&HA5, "Amatsu"},
    {&HA6, "Eruzerion"},
    {&HA7, "Musou Dure"},
    {&HA8, "Rocks"},
    {&HA9, "Seregios"},
    {&HAA, "Bogabadorumu"},
    {&HAB, "Unknown Blue Barrel"},
    {&HAC, "Musou Bogabadorumu"},
    {&HAD, "Costumed Uruki"},
    {&HAE, "Musou Zerureusu"},
    {&HAF, "PSO2 Rappy"},
    {&HB0, "King Shakalaka"}
}
    End Class
End Namespace
